[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | data
  | models
)/
'''

[tool.ruff]
line-length = 120
select = ["E", "F", "B"]
ignore = ["E501"]  # Line length too long

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = ["C0301"]  # Line too long 